- name: yum リポジトリ(epel/remi/ius/fastestmirror/deltarpm) 追加
  yum: 
    name:
      - epel-release
      - https://rpms.remirepo.net/enterprise/remi-release-7.rpm
      - https://repo.ius.io/ius-release-el7.rpm
      - yum-plugin-fastestmirror
      - deltarpm
    state: latest
  tags: yum

- name: yum キャッシュクリア
  file:
    path: /var/cache/yum/x86_64
    state: absent
  tags: yum

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no
  tags: yum

- name: yum update all
  yum: 
    name:
      - '*'
    state: latest
  tags: yum

- name: glibc-common 言語パッケージ/libselinux-python/elinks/lynx/sysstat 追加
  yum: 
    name:
      - glibc-common
      - libselinux-python
      - elinks
      - lynx
      - sysstat
    state: latest
  tags: yum

- name: vim/screen/ncdu/popt-devel/dbench 追加
  yum: 
    name:
      - screen
      - vim
      - ncdu
      - popt-devel
      - dbench
    enablerepo: epel
    state: latest
  tags: yum

- name: cronie-noanacron 追加
  yum: 
    name:
      - cronie-noanacron
    state: latest
  tags: yum

- name: cronie-anacron 削除
  yum: 
    name:
      - cronie-anacron
    state: absent
  tags: yum

- name: Mackerel インストールシェル取得
  get_url:
    url: https://mackerel.io/file/script/setup-all-yum-v2.sh
    dest: /tmp/setup-all-yum-v2.sh
    owner: root
    group: root
    mode: 0755
  tags: yum

- name: Mackerel インストール
  shell: /tmp/setup-all-yum-v2.sh
  environment:
    MACKEREL_APIKEY: "{{ mackerel_apikey }}"
  tags: yum
