- name: fastestmirror 追加/有効化
  yum: 
    name:
      - yum-plugin-fastestmirror
    state: latest
  tags: yum

- name: yum リポジトリ 追加(epel/remi/ius)
  yum: 
    name:
      - epel-release
      - https://rpms.remirepo.net/enterprise/remi-release-7.rpm
      - https://repo.ius.io/ius-release-el7.rpm
    state: latest
  tags: yum

- name: yum update all
  yum: 
    name:
      - '*'
    state: latest
  tags: yum

- name: 言語パッケージ 追加
  yum: 
    name:
      - glibc-common
    state: latest
  tags: yum

- name: libselinux-python 追加
  yum: 
    name:
      - libselinux-python
    state: latest
  tags: yum

- name: vim/screenをインストール
  yum: 
    name:
      - screen
      - vim
    enablerepo: epel
    state: latest
  tags: yum
