- name: yum リポジトリ(epel/remi/ius/fastestmirror/deltarpm) 追加
  yum: 
    name:
      - epel-release
      - https://rpms.remirepo.net/enterprise/remi-release-7.rpm
      - https://repo.ius.io/ius-release-el7.rpm
      - yum-plugin-fastestmirror
      - deltarpm
    state: latest
  tags: yum

- name: yum update all
  yum: 
    name:
      - '*'
    state: latest
  tags: yum

- name: glibc-common 言語パッケージ 追加
  yum: 
    name:
      - glibc-common
    state: latest
  tags: yum

- name: libselinux-python 追加
  yum: 
    name:
      - libselinux-python
    state: latest
  tags: yum

- name: vim/screen/ncdu/popt-devel/dbench 追加
  yum: 
    name:
      - screen
      - vim
      - ncdu
      - popt-devel
      - dbench
    enablerepo: epel
    state: latest
  tags: yum

- name: elinks/lynx/sysstat 追加
  yum: 
    name:
      - elinks
      - lynx
      - sysstat
    state: latest
  tags: yum

- name: cronie-noanacron 追加
  yum: 
    name:
      - cronie-noanacron
    state: latest
  tags: yum

- name: cronie-anacron 削除
  yum: 
    name:
      - cronie-anacron
    state: absent
  tags: yum
