- name: apache グループ作成
  group:
    name: apache
    state: present
  tags:
    - httpd

- name: apache ユーザー作成
  user:
    name: apache
    group: apache
    append: yes
  tags:
    - httpd

- name: /etc/httpd/conf.d/ に .conf コピー
  copy:
    src: "{{ item }}"
    dest: /etc/httpd/conf.d/
    owner: root
    group: root
    mode: 0644
  with_items:
    - notrace.conf
    - deflate.conf
  tags:
    - httpd
    - config

- name: conf.modules.d のバックアップ
  shell: cp -p {{ item }} {{ item }}.default
  args:
    chdir: /etc/httpd/conf.modules.d/
    creates: "{{ item }}.default"
  with_items:
    - 00-base.conf
    - 00-proxy.conf
    # - 10-h2.conf
    # - 10-proxy_h2.conf
  tags:
    - httpd
    - config

- name: conf.modules.d に .conf コピー
  copy:
    src: "{{ item }}"
    dest: /etc/httpd/conf.modules.d/
    owner: root
    group: root
    mode: 0644
  with_items:
    - 00-base.conf
    - 00-proxy.conf
    - 10-h2.conf
    - 10-proxy_h2.conf
  tags:
    - httpd
    - config

- name: DocumentRoot 作成
  file:
    path: "/var/www/{{ doc_root }}"
    owner: "{{ doc_root_owner }}"
    group: "{{ doc_root_owner }}"
    state: directory
    mode: 0755
  tags:
    - httpd
    - config

- name: VirtualHostごとのConfigファイルを作成して転送
  template:
    src: vhost_conf.j2
    dest: "/etc/httpd/conf.d/vhost_{{ server_host_name }}.conf"
    owner: root
    group: root
    mode: 0644
  tags:
    - httpd
    - config

- name: httpd.conf のバックアップ
  shell: cp -p httpd.conf httpd.conf.default
  args:
    chdir: /etc/httpd/conf/
    creates: httpd.conf.default
  tags:
    - httpd
    - config

- name: httpd.conf の作成とコピー
  template:
    src: httpd.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - httpd
    - config

- name: httpd 再起動
  service:
    name: httpd
    state: restarted
    enabled: yes
  tags:
    - httpd
    - config

- name: logrotate.d に httpd コピー
  copy:
    src: httpd.txt
    dest: /etc/logrotate.d/httpd
    owner: root
    group: root
    mode: 0644
  tags:
    - httpd
    - config
