- name: rpm-build, rpmdevtools, yum-utils, gcc パッケージのインストール
  yum: 
    name:
      - rpm-build
      - rpmdevtools
      - yum-utils
      - gcc
    state: latest
  tags:
    - httpd
    - mod_dosdetector

- name: RPMビルド環境初期化
  shell: rpmdev-setuptree
  args:
    chdir: /root/
    creates: rpmbuild
  tags:
    - httpd
    - mod_dosdetector

- name: mod_dosdetector-fork のアーカイヴ取得
  get_url:
    url: "https://github.com/tkyk/mod_dosdetector-fork/archive/{{ mod_dosdetector_ver }}.tar.gz"
    dest: "/root/rpmbuild/SOURCES/mod_dosdetector-fork-{{ mod_dosdetector_ver }}.tar.gz"
    mode: 0644
  tags:
    - httpd
    - mod_dosdetector

- name: mod_dosdetector SPECファイル 取得
  get_url:
    url: "https://raw.githubusercontent.com/tkyk/mod_dosdetector-fork/{{ mod_dosdetector_ver }}/mod_dosdetector-fork.spec"
    dest: /root/rpmbuild/SPECS/mod_dosdetector-fork.spec
    mode: 0644
  tags:
    - httpd
    - mod_dosdetector

- name: mod_dosdetector RPMビルド
  shell: rpmbuild -bb SPECS/mod_dosdetector-fork.spec
  args:
    chdir: /root/rpmbuild/
  tags:
    - httpd
    - mod_dosdetector

- name: mod_dosdetector インストール
  yum:
    name: "/root/rpmbuild/RPMS/x86_64/mod_dosdetector-fork-{{ mod_dosdetector_ver }}-1.x86_64.rpm"
    state: present
  tags:
    - httpd
    - mod_dosdetector

- name: dosdetector.conf のバックアップ
  shell: cp -p dosdetector.conf dosdetector.conf.default
  args:
    chdir: /etc/httpd/conf.d/
    creates: dosdetector.conf.default
  tags:
    - httpd
    - mod_dosdetector

- name: dosdetector.conf コピー
  copy:
    src: dosdetector.conf
    dest: /etc/httpd/conf.d/
    owner: root
    group: root
    mode: 0644
  tags:
    - httpd
    - mod_dosdetector