- name: 依存ライブラリ 追加
  yum: 
    name:
      - nghttp2
      - mailcap
      - brotli
      - openldap-devel
      - expat-devel
      - libdb-devel
      - apr-devel
    state: latest
  tags:
    - httpd
    - package

- name: Apache httpd, http-devel 追加
  yum: 
    name:
      - httpd
      - httpd-devel
    enablerepo: ius
    disablerepo: base,extras,updates,epel
    state: latest
  tags:
    - httpd
    - package