# 共通的な変数を定義
# バージョン情報等

# スワップ領域(MB)
swap_mem_size: 1M

# 作業ユーザー, groupsはカンマ区切りで複数指定可能
workusers:
  - {name: "cypochi", groups: "wheel"}

# MariaDB バージョン
mariadb_ver: 10.3

# Tomcat ホスティング
tomcat_hosting: ftp.riken.jp/net/apache/tomcat/tomcat-8
# Tomcat バージョン
tomcat_ver: 8.5.63

# mod_dosdetector-fork バージョン
mod_dosdetector_ver: 1.1.0