- name: firewalld を停止、無効化
  service:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes
  tags: 
   - iptables
   - package

- name: fail2ban を停止
  service:
    name: fail2ban
    state: stopped
  ignore_errors: yes
  tags: 
   - iptables
   - package

- name: iptables-services 追加
  yum:
    name: iptables-services
    state: latest
  tags: 
   - iptables
   - package
