# CMSサーバー
- hosts: cms
  become: yes
  vars:
    server_host_name: "{{ cms_host_name }}"
    server_ip: "{{ cms_server_ip }}"
    # Apache設定
    max_request: 2048
    doc_root: "{{ cms_doc_root }}"
    doc_root_owner: apache
    # PHP-FPM設定
    pm_max_children: 40
    pm_start_servers: 5
    pm_min_spare_servers: 5
    pm_max_spare_servers: 25
  roles:
    - common
    - httpd
    - php
    - java
    - mariadb